# Global settings
baseURL = 'https://wurining.github.io/MengLuSite'
languageCode = 'en-us'
uglyurls = false
title = 'Meng Lu (Ivan) - Resume'
theme = "m10c"
paginate = 20
# Taxonomies
[taxonomies]
category = 'categories'
tag = 'tags'
# Menu
[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/#main"
weight = 1
[[menu.main]]
identifier = "education"
name = "Education"
url = "/#education"
weight = 2
[[menu.main]]
identifier = "industry"
name = "Industry"
url = "/#industry"
weight = 3
# Parameters
[params]
author = "Meng Lu (Ivan)"
# avatar = ""
menu_item_separator = "-"
favicon = "favicon.png"

phone = "+1 (347) 886-2071"
email = "ivan.lu.usa@gmail.com"
address = "172 Madison Ave, New York, United States"
description = "Experienced in <b>Machine Learning/Natural Language Processing/Computer Vision</b> with demonstrated working experience at the National Laboratory of Pattern Recognition, Chinese Academy of Sciences. Skilled in Pytorch/Python, VBA, Python, Matlab, MySQL, C/C++, creating adversarial attack algorithms, and generating data mining--recommender system tasks. Information extraction from biomedical language and healthcare informatics. <br>Strong computer science and quantitative finance professional with one Master of Science (M.S.) focused in computer science from Northwestern University, and one Master of Science focused on Quantitative Finance from Lancaster University, UK. <br>Green Card Holder."
[[params.social]]
icon = "linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/in/l-ivan-499092166?trk=public_profile_browsemap_profile-result-card_result-card_full-click"
[[params.download]]
name = "CV"
assest = "pdf/cv.pdf"
icon = "download"
[[params.download]]
name = "Project Description"
assest = "pdf/project-description.pdf"
icon = "download"

[params.style]
darkestColor = "#ffffff"
darkColor = "rgb(248,250,252)"
lightColor = "#0a1922"
lightestColor = "#0a1922"
# primaryColor = "rgb(5,148,203)"
primaryColor = "#5594ac"